/**
 * @description       :
 * @author            : Anes BOUZOUINA
 * @group             :
 * @last modified on  : 08-06-2024
 * @last modified by  : Anes BOUZOUINA
**/


public with sharing class Calculator {

    public integer add(integer a, integer b){
        return a+b;
    }


    public integer sub(integer a, integer b){
        return a-b;

    }
    public integer multiple(Integer a, integer b){
        return a*b;
    }

    public integer devide(integer a, integer b){
        return a/b;
    }

    public integer rest(integer a, integer b){
        return ab;
    }


}